- name: Build and analyze with SonarQube
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    mvn clean verify sonar:sonar -Pcoverage \
    -Dsonar.projectKey=David52PG_PalworldBreeder \
    -Dsonar.organization=https://sonarcloud.io/organizations/david52pg \
    -Dsonar.host.url=https://sonarcloud.io