name: SonarQube Analysis
on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama principal
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token de SonarCloud
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de GitHub (automático)
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=David52PG_PalworldBreeder \
            -Dsonar.organization=https://sonarcloud.io/organizations/david52pg \
            -Dsonar.host.url=https://sonarcloud.io